# The name of your project
name: my_app

# A short description of your app
description: A new Flutter project.

# Prevent accidental publishing to pub.dev
publish_to: 'none' # Remove this line if you want to publish the package

# Version number of your app
version: 1.0.0+1

environment:
  # Minimum SDK version required
  sdk: ^3.6.0

#------------------ DEPENDENCIES ------------------#
dependencies:
  # Flutter SDK dependency
  flutter:
    sdk: flutter

  # iOS-style icons package (default)
  cupertino_icons: ^1.0.8
  google_fonts: ^6.3.2
  get: ^4.7.2
  get_storage: ^2.1.1
  share_plus: ^12.0.0
  carousel_slider: ^5.1.1

#------------------ DEV DEPENDENCIES ------------------#
dev_dependencies:
  # Flutter's testing framework
  flutter_test:
    sdk: flutter

  # Recommended lint rules
  flutter_lints: ^5.0.0

#------------------ FLUTTER SETTINGS ------------------#
flutter:
  # Ensures Material Design icons are included
  uses-material-design: true

  # To add assets (like images), uncomment and add file paths below:
  assets:
    - assets/images/

  # To add custom fonts, uncomment and configure below:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
