// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC0qX5NOTmqf1Y3zP2zofMLvpHeB2HkNvU',
    appId: '1:142173901634:android:ab068acb7df84ab37deedb',
    messagingSenderId: '142173901634',
    projectId: 'ecomarce-da93d',
    storageBucket: 'ecomarce-da93d.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCGfEZBWr0TDUFoKAJ2pzax2FCnIqYycmU',
    appId: '1:142173901634:ios:a2c4ceef89ede8bc7deedb',
    messagingSenderId: '142173901634',
    projectId: 'ecomarce-da93d',
    storageBucket: 'ecomarce-da93d.firebasestorage.app',
    iosBundleId: 'com.example.app',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBAkZCRv8mt4Nh7K0j4wQ5U_vwdjzm1bJ8',
    appId: '1:142173901634:web:676533722a2dfcc27deedb',
    messagingSenderId: '142173901634',
    projectId: 'ecomarce-da93d',
    authDomain: 'ecomarce-da93d.firebaseapp.com',
    storageBucket: 'ecomarce-da93d.firebasestorage.app',
    measurementId: 'G-H10T7XBDGD',
  );

}